### ISSUE TITLE
Cyclical sampler broken after random seeds update

### ISSUE THREAD

**Issue by adieyal** [adieyal/dynamicprompts#84]
The implementation of [random seed per image](https://github.com/adieyal/dynamicprompts/blob/main/src/dynamicprompts/generators/randomprompt.py#L68-L72) has broken the cyclical sampler. Since the cyclical sampler stores state, the approach of sampling one prompt at a time won't work. e.g.

`{@red|green|blue} chair` should produce
```
red chair
green chair
blue chart
red chair
...
```

right now it generates
```
red chair
red chair
red chair
...
```

@akx do you have any thoughts on how to implement this? One approach might be to pass the seeds into the sampler itself. Another would be to make the current sampling step resumable, i.e. something like
`
```
sampler.sample_prompts("{@red|green|blue}", num_prompts=4)
sampler.sample_more(num_prompts=5)
```

Thoughts?
```

**Comment by adieyal** [comment]
This request also ask to be able to resume sampling. Implementing that request would need some additional changes in the extension though.

**Comment by Mistborn-First-Era** [comment]
I think it is related to this so I am posting it here. After I updated I keep getting an error whenever I generate an image with dynamic prompts enabled, but I am not using any dynamic prompts. 

```
Error running process: C:\Users\Brandon\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
Traceback (most recent call last):
  File "C:\Users\Brandon\stable-diffusion-webui\modules\scripts.py", line 418, in process
    script.process(p, *script_args)
  File "C:\Users\Brandon\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 440, in process
    all_prompts, all_negative_prompts = generate_prompts(
  File "C:\Users\Brandon\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
    all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
TypeError: RandomPromptGenerator.generate() got an unexpected keyword argument 'seeds'
```
The error pops up in my console\terminal between every generation including hires.fix it's very annoying and it probably is breaking something I haven't tested yet. For now I am just keeping it disabled and the error is not popping up.

**Comment by adieyal** [comment]
@Mistborn-First-Era no - that issue is unrelated. Have a look at this issue: https://github.com/adieyal/sd-dynamic-prompts/issues/441

**Comment by akx** [comment]
@adieyal Well...`sample_prompts` is a generator, so we could probably just do

```python
gen = self._context.sample_prompts(template)
for seed in seeds:
    self._context.rand.seed(seed)
    gen = self._context.sample_prompts(template, 1)
    prompts.append(next(gen))
return prompts
```
to tweak the RNG seed while keeping all of the other context the same..?

**Comment by adieyal** [comment]
good point
