### ISSUE TITLE
Error with wildcards

### ISSUE THREAD

**Issue by Kaneda56** [adieyal/dynamicprompts#93]
I have an error when I'm using wildcards :

```
Error running process: S:\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
Traceback (most recent call last):
  File "S:\stable-diffusion-webui\modules\scripts.py", line 451, in process
    script.process(p, *script_args)
  File "S:\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 478, in process
    all_prompts, all_negative_prompts = generate_prompts(
  File "S:\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
    all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
  File "S:\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\generators\randomprompt.py", line 67, in generate
    gen = self._context.sample_prompts(template, num_images)
  File "S:\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\sampling_context.py", line 119, in sample_prompts
    command = parse(prompt, parser_config=self.parser_config)
  File "S:\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\parser\parse.py", line 454, in parse
    tokens = get_cached_parser(parser_config).parse_string(
  File "S:\stable-diffusion-webui\venv\lib\site-packages\pyparsing\core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected end of text, found '_'  (at char 113), (line:1, col:114)
```
How to fix it ?
Thanks

**Comment by akx** [comment]
Your prompt is malformed somehow (but since you're not showing it, it's hard to tell how).

**Comment by Kaneda56** [comment]
Thank you very much indeed. I hadn't paid attention
